export const LOAD_RESULTS_STARTED = 'LOAD_RESULTS_STARTED'
export const LOAD_RESULTS_FAILED = 'LOAD_RESULTS_FAILED'
export const LOAD_RESULTS_SUCCESS = 'LOAD_RESULTS_SUCCESS'
export const RESET_STORE = 'RESET_STORE'
